GRANT ALL PRIVILEGES ON grupo_1.* TO 'adrian'@'	92.168.1.102' IDENTIFIED BY '875875' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON grupo_1.* TO 'tamara'@'%' IDENTIFIED BY '12345' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON grupo_1.* TO 'elena'@'%' IDENTIFIED BY '12345' WITH GRANT OPTION;